// tests/unit/list-tasks.test.mjs
//
// Tests for bin/list-tasks.mjs — lists local tasks created by /jlu-new-task by
// scanning <workspace>/specs/<date>/<slug>/ and parsing TASKS.md + SPEC.md.
//
// Run: `node --test tests/unit/list-tasks.test.mjs`

import { test, describe } from 'node:test';
import { strict as assert } from 'node:assert';
import { spawnSync } from 'node:child_process';
import { mkdtempSync, mkdirSync, writeFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { resolveWorkspace, listTasks, renderTable } from '../../bin/list-tasks.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));
const SCRIPT = join(HERE, '..', '..', 'bin', 'list-tasks.mjs');

// --- canonical TASKS.md as written by /jlu-new-task ---
const CANONICAL_TASKS = `# Task: add-auth-gate

## Status: planned

## Lifecycle
- Created: 2026-06-15T10:00:00Z
- Sprint: 7

## Services
- Primary: jelou-api
- Affected: chatbot-server, workflows-server

## Phases
(pending — will be generated by /jlu-execute-task)
`;

// --- alternative TASKS.md (lifecycle-in-section + frontmatter services) ---
const ALT_TASKS = `---
affected_services:
  - id: service-postgres
    sub_state: planned
  - id: service-billing
    sub_state: planned
---

# Tasks — Cancel pro subscription

## Status
- **Lifecycle**: implementing
- **Sprint**: 3

## Branching
- **Mode**: branch
`;

function makeWorkspace(tasks) {
  const root = mkdtempSync(join(tmpdir(), 'list-tasks-'));
  const ws = join(root, '.spec-workspace');
  for (const t of tasks) {
    const dir = join(ws, 'specs', t.date, t.slug);
    mkdirSync(dir, { recursive: true });
    if (t.tasksMd !== undefined) writeFileSync(join(dir, 'TASKS.md'), t.tasksMd);
    if (t.specMd !== undefined) writeFileSync(join(dir, 'SPEC.md'), t.specMd);
  }
  // ensure specs/ exists even with no tasks
  mkdirSync(join(ws, 'specs'), { recursive: true });
  return { root, ws };
}

describe('list-tasks — listTasks()', () => {
  test('empty workspace returns no tasks', () => {
    const { ws } = makeWorkspace([]);
    assert.deepEqual(listTasks(ws), []);
  });

  test('parses canonical /jlu-new-task TASKS.md (slug, date, title, status, sprint, services)', () => {
    const { ws } = makeWorkspace([
      {
        date: '15-06-2026',
        slug: 'add-auth-gate',
        tasksMd: CANONICAL_TASKS,
        specMd: '# Add auth gate\n\nGate the dashboard behind OTP.\n',
      },
    ]);
    const tasks = listTasks(ws);
    assert.equal(tasks.length, 1);
    const t = tasks[0];
    assert.equal(t.slug, 'add-auth-gate');
    assert.equal(t.date, '15-06-2026');
    assert.equal(t.title, 'Add auth gate');
    assert.equal(t.status, 'planned');
    assert.equal(t.sprint, '7');
    assert.deepEqual(t.services, ['jelou-api', 'chatbot-server', 'workflows-server']);
  });

  test('parses alternative format: lifecycle-in-section + frontmatter affected_services', () => {
    const { ws } = makeWorkspace([
      {
        date: '10-06-2026',
        slug: 'cancel-subscription',
        tasksMd: ALT_TASKS,
        specMd: '# Cancel pro subscription\n\nUser cancels and sees a banner.\n',
      },
    ]);
    const [t] = listTasks(ws);
    assert.equal(t.status, 'implementing');
    assert.equal(t.sprint, '3');
    assert.equal(t.title, 'Cancel pro subscription');
    assert.deepEqual(t.services, ['service-postgres', 'service-billing']);
  });

  test('title falls back to slug when SPEC.md is missing', () => {
    const { ws } = makeWorkspace([
      { date: '15-06-2026', slug: 'no-spec-task', tasksMd: CANONICAL_TASKS },
    ]);
    const [t] = listTasks(ws);
    assert.equal(t.title, 'no-spec-task');
  });

  test('status is "unknown" when no status marker is present', () => {
    const { ws } = makeWorkspace([
      { date: '15-06-2026', slug: 'bare-task', tasksMd: '# Task: bare-task\n' },
    ]);
    const [t] = listTasks(ws);
    assert.equal(t.status, 'unknown');
  });

  test('directory without TASKS.md is not a task and is ignored', () => {
    const { ws } = makeWorkspace([
      { date: '15-06-2026', slug: 'real-task', tasksMd: CANONICAL_TASKS },
      { date: '15-06-2026', slug: 'just-a-folder', specMd: '# Stray\n' },
    ]);
    const slugs = listTasks(ws).map((t) => t.slug);
    assert.deepEqual(slugs, ['real-task']);
  });

  test('"(pending detection)" affected list yields only the primary service', () => {
    const tasksMd = `# Task: solo\n\n## Status: refining\n\n## Services\n- Primary: jelou-api\n- Affected: (pending detection)\n`;
    const { ws } = makeWorkspace([{ date: '15-06-2026', slug: 'solo', tasksMd }]);
    const [t] = listTasks(ws);
    assert.deepEqual(t.services, ['jelou-api']);
  });

  test('dates across different months sort by calendar date, not by day of month', () => {
    const { ws } = makeWorkspace([
      { date: '31-03-2026', slug: 'march', tasksMd: CANONICAL_TASKS },
      { date: '30-06-2026', slug: 'june', tasksMd: CANONICAL_TASKS },
      { date: '01-12-2025', slug: 'december', tasksMd: CANONICAL_TASKS },
    ]);
    const ordered = listTasks(ws).map((t) => t.slug);
    assert.deepEqual(ordered, ['june', 'march', 'december']);
  });

  test('multiple tasks are sorted by date desc then slug asc', () => {
    const { ws } = makeWorkspace([
      { date: '10-06-2026', slug: 'older', tasksMd: CANONICAL_TASKS },
      { date: '15-06-2026', slug: 'beta', tasksMd: CANONICAL_TASKS },
      { date: '15-06-2026', slug: 'alpha', tasksMd: CANONICAL_TASKS },
    ]);
    const ordered = listTasks(ws).map((t) => `${t.date}/${t.slug}`);
    assert.deepEqual(ordered, ['15-06-2026/alpha', '15-06-2026/beta', '10-06-2026/older']);
  });
});

describe('list-tasks — resolveWorkspace()', () => {
  test('reads the workspace path from .spec-workspace.json', () => {
    const { root, ws } = makeWorkspace([]);
    const project = mkdtempSync(join(tmpdir(), 'list-tasks-proj-'));
    writeFileSync(join(project, '.spec-workspace.json'), JSON.stringify({ workspace: ws }));
    assert.equal(resolveWorkspace(project), ws);
    rmSync(root, { recursive: true, force: true });
    rmSync(project, { recursive: true, force: true });
  });

  test('finds .spec-workspace/ by walking up from a nested directory', () => {
    const { ws } = makeWorkspace([]);
    const nested = join(dirname(ws), 'a', 'b', 'c');
    mkdirSync(nested, { recursive: true });
    assert.equal(resolveWorkspace(nested), ws);
  });

  test('returns null when no workspace can be found', () => {
    const lonely = mkdtempSync(join(tmpdir(), 'list-tasks-none-'));
    assert.equal(resolveWorkspace(lonely), null);
    rmSync(lonely, { recursive: true, force: true });
  });
});

describe('list-tasks — renderTable()', () => {
  test('empty list renders a "no tasks" message, not a header row', () => {
    const out = renderTable([]);
    assert.match(out, /no tasks/i);
  });

  test('renders headers and a task row', () => {
    const out = renderTable([
      { slug: 'add-auth-gate', date: '15-06-2026', title: 'Add auth gate', status: 'planned', sprint: '7', services: ['jelou-api'] },
    ]);
    assert.match(out, /Slug/);
    assert.match(out, /Status/);
    assert.match(out, /add-auth-gate/);
    assert.match(out, /Add auth gate/);
    assert.match(out, /planned/);
    assert.match(out, /jelou-api/);
  });
});

describe('list-tasks — CLI', () => {
  test('--workspace with --json prints a JSON array', () => {
    const { ws } = makeWorkspace([
      { date: '15-06-2026', slug: 'add-auth-gate', tasksMd: CANONICAL_TASKS, specMd: '# Add auth gate\n' },
    ]);
    const r = spawnSync('node', [SCRIPT, '--workspace', ws, '--json'], { encoding: 'utf8' });
    assert.equal(r.status, 0, r.stderr);
    const parsed = JSON.parse(r.stdout);
    assert.ok(Array.isArray(parsed));
    assert.equal(parsed[0].slug, 'add-auth-gate');
  });

  test('exits non-zero when no workspace can be resolved', () => {
    const lonely = mkdtempSync(join(tmpdir(), 'list-tasks-cli-none-'));
    const r = spawnSync('node', [SCRIPT, '--cwd', lonely], { encoding: 'utf8' });
    assert.notEqual(r.status, 0);
    assert.match(r.stderr, /workspace/i);
    rmSync(lonely, { recursive: true, force: true });
  });

  test('--status filters tasks by lifecycle state', () => {
    const { ws } = makeWorkspace([
      { date: '15-06-2026', slug: 'planned-one', tasksMd: CANONICAL_TASKS },
      { date: '15-06-2026', slug: 'building', tasksMd: ALT_TASKS },
    ]);
    const r = spawnSync('node', [SCRIPT, '--workspace', ws, '--json', '--status', 'implementing'], { encoding: 'utf8' });
    assert.equal(r.status, 0, r.stderr);
    const parsed = JSON.parse(r.stdout);
    assert.deepEqual(parsed.map((t) => t.slug), ['building']);
  });
});

describe('list-tasks — stdout survives a real pipe', () => {
  const PIPE_BUFFER = 64 * 1024;
  const WIDE_COUNT = 900;

  function wideWorkspace() {
    const root = mkdtempSync(join(tmpdir(), 'list-tasks-wide-'));
    const ws = join(root, '.spec-workspace');
    for (let i = 1; i <= WIDE_COUNT; i++) {
      const day = String((i % 28) + 1).padStart(2, '0');
      const month = String((i % 12) + 1).padStart(2, '0');
      const dir = join(ws, 'specs', `${day}-${month}-2026`, `wide-${String(i).padStart(4, '0')}`);
      mkdirSync(dir, { recursive: true });
      writeFileSync(join(dir, 'TASKS.md'), CANONICAL_TASKS);
      writeFileSync(join(dir, 'SPEC.md'), `# Derivación de estado y trazabilidad ${i}\n`);
    }
    return { root, ws };
  }

  function pipedCli(args) {
    return spawnSync('bash', ['-c', 'set -o pipefail; "$0" "$@" | cat', process.execPath, SCRIPT, ...args], {
      encoding: 'utf8',
      maxBuffer: 64 * 1024 * 1024,
    });
  }

  function earlyCloseCli(args) {
    return spawnSync('bash', ['-c', '"$0" "$@" | head -c 100', process.execPath, SCRIPT, ...args], {
      encoding: 'utf8',
      maxBuffer: 64 * 1024 * 1024,
    });
  }

  test('--json delivers every row through a pipe when it outgrows the pipe buffer', () => {
    const { root, ws } = wideWorkspace();
    const direct = spawnSync('node', [SCRIPT, '--workspace', ws, '--json'], { encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 });
    assert.equal(direct.status, 0, direct.stderr);
    const size = Buffer.byteLength(direct.stdout);
    assert.ok(size > PIPE_BUFFER + 1024, `the fixture must outgrow one pipe buffer, got ${size} bytes`);

    const piped = pipedCli(['--workspace', ws, '--json']);
    assert.equal(piped.status, 0, piped.stderr);
    assert.equal(Buffer.byteLength(piped.stdout), size);
    assert.equal(JSON.parse(piped.stdout).length, WIDE_COUNT);
    rmSync(root, { recursive: true, force: true });
  });

  test('the table survives a pipe once it outgrows the pipe buffer', () => {
    const { root, ws } = wideWorkspace();
    const direct = spawnSync('node', [SCRIPT, '--workspace', ws], { encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 });
    assert.equal(direct.status, 0, direct.stderr);
    assert.ok(Buffer.byteLength(direct.stdout) > PIPE_BUFFER + 1024, 'the fixture must outgrow one pipe buffer');

    const piped = pipedCli(['--workspace', ws]);
    assert.equal(piped.status, 0, piped.stderr);
    assert.equal(Buffer.byteLength(piped.stdout), Buffer.byteLength(direct.stdout));
    rmSync(root, { recursive: true, force: true });
  });

  test('a consumer that closes the pipe early gets no stack trace and no error output', () => {
    const { root, ws } = wideWorkspace();
    for (const args of [['--workspace', ws, '--json'], ['--workspace', ws]]) {
      const r = earlyCloseCli(args);
      assert.equal(r.stderr, '', `expected silence on stderr, got: ${r.stderr}`);
    }
    rmSync(root, { recursive: true, force: true });
  });
});
